services:
  postgres:
    image: postgres:16-alpine
    container_name: nest_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: hiro_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # ◄ This creates the separate, persistent volume on your machine